insert into TODOLIST (ID,STATUS,TARGET_DATE,DESCRIPTION,USERNAME)
values (1001,false,CURRENT_DATE(),'GET AWS CERTIFIED','emadd9');

insert into TODOLIST (ID,STATUS,TARGET_DATE,DESCRIPTION,USERNAME)
values (1002,false,CURRENT_DATE(),'GET Azure CERTIFIED','emadd9');

insert into TODOLIST (ID,STATUS,TARGET_DATE,DESCRIPTION,USERNAME)
values (1003,false,CURRENT_DATE(),'GET GCP CERTIFIED','emadd9');

insert into TODOLIST (ID,STATUS,TARGET_DATE,DESCRIPTION,USERNAME)
values (1004,false,CURRENT_DATE(),'GET DevOps CERTIFIED','emadd9');